---

extra_includes:
- PyTrajectoryConstraint.h

classes:
  TrajectoryConfig:
    shared_ptr: true
    methods:
      TrajectoryConfig:
      SetStartVelocity:
      SetEndVelocity:
      SetReversed:
      AddConstraint:
        template_impls:
        - [PyTrajectoryConstraint]
      SetKinematics:
        overloads:
          DifferentialDriveKinematics&:
          MecanumDriveKinematics:
          SwerveDriveKinematics<NumModules>&:
            ignore: true
      StartVelocity:
      EndVelocity:
      MaxVelocity:
      MaxAcceleration:
      Constraints:
        ignore: true # seems hard, let me know if you need it
      IsReversed:
